### ISSUE TITLE
QUESTION: Is it possible to fetch data automatically?

### ISSUE THREAD

**Issue by roefy** [testo/tjf#1]
I did create an app which asks data from the Testo Smart Probes app via the App2App protocol. Is it possible to get the actual measuring points automatically (like through an extra parameter into the calling URL) in stead of pressing the "export" button in the app?

P.s. I was not able to add the "question" label to this issue.

**Comment by gwaldvogel** [comment]
Hi @roefy, unfortunately that is not possible right now, as most measurements require some form of user input.
If you want to describe your use case in more detail I would be happy to open a feature request for you.

**Comment by roefy** [comment]
@gwaldvogel Hmm, that's bad for us, because we bought some Smart Probes sets for using them by us on the R&D department. Well, let's descripe our use case:
We have writen a measurement system in which we read out a lot of devices and save the data of them on a computer. You must think about devices for logging Pt100, thermocouples, analog values, power loggers, CO/CO2 meters, etc. All of them via the network serial connection or modbus. It would be nice if we can add the Testo Smart probes to our system.
What I want is a option to get every second the last measured value of the probe. The dev2dev protocol support this, right? So, maybe it is possible to add this protocol to the Testo Smart app? Or is this already implemented, while I saw an network option in the app?

**Comment by roefy** [comment]
@gwaldvogel I got some other information from your colleague in The Netherlands which helps me a lot. It works now like I described above. Thanks for your time and information!

**Comment by andreasharbo** [comment]
Hi, sorry to post on a closed issue, but I have just asked a similar question in a new issue. Do you think you, @roefy can relay the information you got from the colleague, here? :)

Cheers

**Comment by roefy** [comment]
I make use of the same API which @gwaldvogel describes in issue https://github.com/testo/tjf/issues/18. So that should work.
