### ISSUE TITLE
Help needed with decoding QR binary data for testo-300 

### ISSUE THREAD

**Issue by Bruineb** [testo/tjf#19]
Hi,

We are trying to implement the testo-300 data in our application via QR code. But we don't know how to interpret the data from the qr code.  Can you Explain me in which format this is and how to decode it?

Yours sincerely,

Developer
Syntess Software B.V.

**Comment by 1000len-stpa** [comment]
Hi @Bruineb,

please have a look at : [https://developers.testo.dev/t300/qrcode/](https://developers.testo.dev/t300/qrcode/) where you should find all information you need.

Best regards,
Patrick

**Comment by Bruineb** [comment]
thank you
