### ISSUE TITLE
Issue reading qrcode from a c# project and zxing net

### ISSUE THREAD

**Issue by Zendrow** [testo/tjf#21]
Hello, 

I'm trying to integrate the qr code reading module via zxing.net for a C# project. 
Unfortunately, it is not possible to unzip the bin file read from an image. 

I think it is due to some error during the decoding of the binary file read by qrcode, because I can unpack the test file you put on the site into json without problems. [TESTO 300 Qr code](https://developers.testo.dev/t300/qrcode/)

Below I'll leave the sample on github about the issue.

[Zendrow/Testo300-qrcode](https://github.com/Zendrow/Testo300-qrcode)

**Comment by 1000len-stpa** [comment]
Hello Riccardo,

sorry for the late reply.
Please check if the content of the QR Code is correctly written to the file. Using the example QR Code you should get 1352 bytes. Maybe there is a Problem that some data get lost the way you write to file, try using File.WriteAllBytes or something similar that does not uses text but bytes. 

Best regards Patrick

**Comment by Zendrow** [comment]
Hi Patrick, 

thanks for the reply. Actually looking at the file size, the program generated a bigger one. We were able to recreate the correct file and retrieve the json. 

Best regards Riccardo
