### ISSUE TITLE
Help Needed with testoApi.yaml

### ISSUE THREAD

**Issue by pbzek** [testo/tjf#3]
Hi,

We are trying to deliver a solution to our client that requires 2 things. 1) They don't want their users to have installed any other app like your apps for reading testo devices. 2) The solution must be provided for testo devices with WIFI and devices with BlueTooth.

As far as we understand we can make use of your open api as you explain in the testoApi.yaml. We can call the api calling either the device or the phone with the installed testo app. As we don't want to use this testo apps, the only way we have is calling the api from our app to your testo devices, but we still need the device IP to make the request. Is there any way we can find the IP of the device? Are you referring to the local IP the device will have when it connects to our phone when sharing internet data? Is this solution suitable to read data from devices connected with bluetooth?

Thanks in advance for your help!

**Comment by gwaldvogel** [comment]
Hi @pbzek 
> Is there any way we can find the IP of the device?

While connected to the local network the testo devices (testo 300 & testo 400) periodically send a UDP broadcast, which can be used to find the IP of the device.

> Are you referring to the local IP the device will have when it connects to our phone when sharing internet data?

Yes, you can access the API by using the local IP with port 54000 or 55000 for the testo 400 and testo 300 respectively.

> Is this solution suitable to read data from devices connected with bluetooth?

This solution is only suitable for the bluetooth devices that can be connected directly to the testo 300 and testo 400. If you want data from other devices you will have to use [testo Smart](https://www.testo.com/en/testo-smart-app/p/0501-5001) which offers the same API as testo 400.

One more thing: If you are using a testo 400, there is currently no up to date documentation for a live measurement data endpoint, we are working on it. Try `GET /api/data/live` to fetch the measurement data.

**Comment by pbzek** [comment]
Hi @gwaldvogel ,

Thanks in advance for your quick and clear response, so as you said, this will only work with two type of devices 300 & 400, so a device 330-2 wont be able to get the data from the API, right?

I was able to listen to UDP broadcast on port 55000 and tried connected to a 330-2 device via bluetooth but didn't received any broadcast. Using "testo combustion" app i successfully reached to get data from that device.

> This solution is only suitable for the bluetooth devices that can be connected directly to the testo 300 and testo 400. If you want data from other devices you will have to use [testo Smart](https://www.testo.com/en/testo-smart-app/p/0501-5001) which offers the same API as testo 400.

So i think in my case, if devices are others different from testo 300 or 400 i can't use this API to get the data.

Many thanks for your help.

**Comment by gwaldvogel** [comment]
Hi @pbzek
You can not directly connect to a testo 330-2, but instead need to use the testo Combustion App.
You can then use a similar API provided by the Combustion app. It should listen to port 53757 and you should be able to receive the data from a compatible device on the `/data` endpoint.

**Comment by pbzek** [comment]
Hi @gwaldvogel,

Great, this is working for me getting the data from the Combustion App on port 53757. 

Thanks for your time and your effort.

Cheers!
